title:              Remix Framework Book
email:              email@remixbook.com
description:        "Full Stack Development with React and Remix: Learn to build apps using web fundamentals"
author:             Ahmed Bouchefra
baseurl:            "/"
url:                "http://remixframework.com"

# Social Profiles
twitter_username:   techiediaries
github_username:    techiediaries
facebook_username:  techiediaries9
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
